# Generated by Django 5.1.2 on 2025-01-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32)),
                ('url', models.URLField(blank=True, max_length=256)),
                ('icon', models.ImageField(blank=True, max_length=32, upload_to='')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.menu')),
            ],
        ),
    ]
