# Generated by Django 5.1.2 on 2025-01-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menuitem_priority_alter_menuitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='menu_app.menu'),
        ),
    ]
