# Generated by Django 5.1.2 on 2024-11-04 08:45

import public_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0005_croppedimage_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CroppedImage',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=public_app.models.path_and_rename),
        ),
    ]
