# Generated by Django 5.1.2 on 2024-12-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
